# Generated by Django 5.1 on 2024-08-18 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessman', '0002_user_latitude_user_longitude_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'wmv', 'png', 'jpg'])]),
        ),
    ]
